import type { Metadata } from "next"
import "./globals.css"
import ShaderGradientBackground from "@/components/ui/shader-gradient"
import LoadingScreen from "@/components/ui/loading-screen"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <ShaderGradientBackground />
        <LoadingScreen />
      </body>
    </html>
  )
}
